apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: fastapi_database
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: password