apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast
spec:
  selector:
    matchLabels:
      app: fast
  template:
    metadata:
      labels:
        app: fast
    spec:
      containers:
      - name: fast
        image: allaismail/backend-contact:latest
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_IP
          value: postgres-service 
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: fastapi_database
        ports:
        - containerPort: 3000

